/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// 1. 定義硬體位址 (STM32F407)
#define RCC_AHB1ENR  (*(volatile uint32_t *)(0x40023830))
#define GPIOD_MODER  (*(volatile uint32_t *)(0x40020C00))
#define GPIOD_ODR    (*(volatile uint32_t *)(0x40020C14))

// 2. 定義跳轉目標位址 (這就是你剛才 App2 改的地方)
#define APP2_START_ADDRESS 0x08008000

// 定義函式指標型態
typedef void (*pFunction)(void);

void delay(void) {
    for(volatile uint32_t i = 0; i < 500000; i++);
}

int main(void) {
    // --- 第一部分：閃紅燈 5 次 (大約 5 秒) ---
    RCC_AHB1ENR |= (1 << 3);    // 開啟 GPIOD 時鐘
    GPIOD_MODER |= (1 << 26);   // 設定 PD13 為輸出 (紅燈)
    GPIOD_MODER &= ~(1 << 27);

    for(int i = 0; i < 10; i++) {
        GPIOD_ODR ^= (1 << 13); // 切換紅燈狀態
        delay();
    }


    // 1. 解鎖 Flash (密鑰是硬體固定的)
    *(volatile uint32_t *)(0x40023C04) = 0x45670123; // FLASH_KEY1
    *(volatile uint32_t *)(0x40023C04) = 0xCDEF89AB; // FLASH_KEY2

    // 2. 擦除 Sector 11 (為了安全，寫入前必做)
    while ((*(volatile uint32_t *)(0x40023C0C)) & (1 << 16)); // 等待忙碌 (BSY)
    *(volatile uint32_t *)(0x40023C10) = (1 << 1) | (11 << 3); // 選擇 Sector 11
    *(volatile uint32_t *)(0x40023C10) |= (1 << 16);           // 開始擦除 (STRT)
    while ((*(volatile uint32_t *)(0x40023C0C)) & (1 << 16)); // 等待結束

    // 3. 寫入資料 (假設寫入 4 個字節: 'V', '1', '.', '0')
    *(volatile uint32_t *)(0x40023C10) = (1 << 0);            // 啟用程式化模式 (PG)
    *(volatile uint32_t *)(0x40023C10) &= ~(3 << 8);
    *(volatile uint32_t *)(0x40023C10) |= (2 << 8);
    *(volatile uint32_t *)(0x080E0000) = 0x302E3156;           // 寫入 "V1.0" 的 ASCII
    while ((*(volatile uint32_t *)(0x40023C0C)) & (1 << 16)); // 等待結束

    // 4. 重新上鎖
    *(volatile uint32_t *)(0x40023C10) |= (1 << 31);          // LOCK

    // --- 第二部分：執行跳轉 ---

    // A. 取得 App2 的執行起點 (Reset Vector)
    // 記得我們討論過的 +4 嗎？
    uint32_t JumpAddress = *(volatile uint32_t *)(APP2_START_ADDRESS + 4);
    pFunction Jump = (pFunction)JumpAddress;

    // B. 設定堆疊指標 (MSP)
    // 直接讀取 App2 起始位址存放的值
    uint32_t msp_value = *(volatile uint32_t *)(APP2_START_ADDRESS);
    __asm volatile ("MSR msp, %0" : : "r" (msp_value) : );

    // C. 正式跳轉
    Jump();

    while(1); // 永遠不會執行到這
}
