/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// 定義 RCC 與 GPIOD 寄存器位址 (以 STM32F407 為例)
#define RCC_AHB1ENR  (*(volatile uint32_t *)(0x40023830))
#define GPIOD_MODER  (*(volatile uint32_t *)(0x40020C00))
#define GPIOD_ODR    (*(volatile uint32_t *)(0x40020C14))

void delay(void) {
    for(volatile uint32_t i = 0; i < 200000; i++);
}

int main(void)
{

	*((volatile uint32_t *)(0xE000ED08)) = 0x08008000; // 這就是 SCB->VTOR
    // 1. 開啟 GPIOD 的時鐘 (F407 的 LED 在 PORT D)
    RCC_AHB1ENR |= (1 << 3);

    // 2. 設定 PD12 為輸出模式 (綠色 LED)
    GPIOD_MODER |= (1 << 24);
    GPIOD_MODER &= ~(1 << 25);

    /* Loop forever */
    while(1) {
        GPIOD_ODR ^= (1 << 12); // 切換 PD12 電位 (閃爍)
        delay();
    }
}
